import * as fs from 'fs';
import * as path from 'path';
import * as cdk from 'aws-cdk-lib/core';
import * as s3 from 'aws-cdk-lib/aws-s3';
import * as cloudfront from 'aws-cdk-lib/aws-cloudfront';
import * as cloudfront_origins from 'aws-cdk-lib/aws-cloudfront-origins';
import * as s3deploy from 'aws-cdk-lib/aws-s3-deployment';
import * as acm from 'aws-cdk-lib/aws-certificatemanager';
import * as route53 from 'aws-cdk-lib/aws-route53';
import * as targets from 'aws-cdk-lib/aws-route53-targets';
import { Construct } from 'constructs';

export interface FrontendSiteStackProps extends cdk.StackProps {
  /**
   * Directory holding the built frontend bundle to upload. Defaults to
   * `frontend-react/dist` relative to this file. If it does not exist at synth
   * time (e.g. CI before a build), the `BucketDeployment` is skipped so
   * `cdk synth` never fails — the deploy orchestrator builds it first.
   */
  readonly distPath?: string;
  /**
   * Route 53 hosted zone for the PRAXIS domain (see DnsStack). Only needed when
   * `domainName` is set to serve the site on a custom domain.
   */
  readonly hostedZone?: route53.IHostedZone;
  /**
   * Custom hostname for the dashboard (e.g. `app.praxiskg.com`). When set
   * (together with `hostedZone`), CloudFront is fronted by an ACM cert plus a
   * Route 53 alias record — but the cert must live in us-east-1 (a hard
   * CloudFront constraint), so that path requires a us-east-1 deploy. When
   * omitted (the default), the site is served on CloudFront's autogenerated
   * `*.cloudfront.net` URL with its default cert, which works from any region
   * and needs no DNS.
   */
  readonly domainName?: string;
}

/**
 * Static hosting for the PRAXIS frontend SPA.
 *
 * A private S3 bucket (no public access) holds the built Vite bundle and is
 * served through a CloudFront distribution using Origin Access Control. Viewer
 * requests are forced to HTTPS, and 403/404 responses are rewritten to
 * `/index.html` (200) so client-side routing on deep links works.
 *
 * The bucket is DESTROY + autoDeleteObjects since it only holds rebuildable
 * assets, making teardown trivial.
 */
export class FrontendSiteStack extends cdk.Stack {
  public readonly bucket: s3.Bucket;
  public readonly distribution: cloudfront.Distribution;

  constructor(scope: Construct, id: string, props: FrontendSiteStackProps) {
    super(scope, id, props);

    const domainName = props.domainName;
    const useCustomDomain = Boolean(domainName && props.hostedZone);

    // A custom domain on CloudFront needs an ACM cert in us-east-1 (a hard
    // CloudFront constraint) plus a DNS-validated Route 53 record. Both are
    // gated behind an explicitly-provided domain; the default path serves on
    // CloudFront's autogenerated *.cloudfront.net URL with its default cert, so
    // the stack deploys cleanly from any region with no DNS.
    const certificate = useCustomDomain
      ? new acm.Certificate(this, 'SiteCert', {
          domainName: domainName!,
          validation: acm.CertificateValidation.fromDns(props.hostedZone!),
        })
      : undefined;

    this.bucket = new s3.Bucket(this, 'SiteBucket', {
      blockPublicAccess: s3.BlockPublicAccess.BLOCK_ALL,
      encryption: s3.BucketEncryption.S3_MANAGED,
      removalPolicy: cdk.RemovalPolicy.DESTROY,
      autoDeleteObjects: true,
    });

    this.distribution = new cloudfront.Distribution(this, 'SiteDistribution', {
      ...(useCustomDomain ? { domainNames: [domainName!], certificate } : {}),
      defaultRootObject: 'index.html',
      defaultBehavior: {
        origin: cloudfront_origins.S3BucketOrigin.withOriginAccessControl(this.bucket),
        viewerProtocolPolicy: cloudfront.ViewerProtocolPolicy.REDIRECT_TO_HTTPS,
      },
      errorResponses: [
        {
          httpStatus: 403,
          responseHttpStatus: 200,
          responsePagePath: '/index.html',
        },
        {
          httpStatus: 404,
          responseHttpStatus: 200,
          responsePagePath: '/index.html',
        },
      ],
    });

    const distPath = props.distPath ?? path.join(__dirname, '../../frontend-react/dist');
    if (fs.existsSync(distPath)) {
      new s3deploy.BucketDeployment(this, 'DeploySite', {
        sources: [s3deploy.Source.asset(distPath)],
        destinationBucket: this.bucket,
        distribution: this.distribution,
        distributionPaths: ['/*'],
      });
    }

    // Custom-domain alias records — only when a domain + zone were supplied.
    if (useCustomDomain) {
      new route53.ARecord(this, 'SiteAliasRecord', {
        zone: props.hostedZone!,
        recordName: domainName!,
        target: route53.RecordTarget.fromAlias(new targets.CloudFrontTarget(this.distribution)),
      });
      new route53.AaaaRecord(this, 'SiteAliasRecordIpv6', {
        zone: props.hostedZone!,
        recordName: domainName!,
        target: route53.RecordTarget.fromAlias(new targets.CloudFrontTarget(this.distribution)),
      });
    }

    const siteUrl = useCustomDomain
      ? `https://${domainName}`
      : `https://${this.distribution.distributionDomainName}`;
    new cdk.CfnOutput(this, 'SiteUrl', { value: siteUrl });
    new cdk.CfnOutput(this, 'DistributionUrl', {
      value: `https://${this.distribution.distributionDomainName}`,
    });
    new cdk.CfnOutput(this, 'SiteBucketName', { value: this.bucket.bucketName });
  }
}
