"""Automatic exemption-manifest derivation for af-clean (R3).

af-clean must never propose deleting/rewriting a path that is generated, vendored, a
lockfile, or a language-convention immutable/fixture directory. Curating that list by hand
per target repo does not scale (af-clean's primary use is arbitrary repositories it has
never seen), so the manifest is DERIVED from seven signals, each contributing entries it can
justify from evidence in the repo -- never a silently hand-authored allowlist:

  1. ``.gitignore`` (incl. nested ones) -- every non-negated pattern is a repo-declared
     "this is build/derived output" signal, whether or not the path currently exists on disk
     (a not-yet-built ``infra/cdk.out/`` is still exempt once it appears).
  2. ``.gitattributes`` ``linguist-generated`` / ``linguist-vendored`` markers, resolved
     against the tracked file set.
  3. Generated / "DO NOT EDIT" content markers (``@generated``, "auto-generated", "Code
     generated by", well-known dump-file headers such as "PostgreSQL database dump") sniffed
     from the head of each tracked file.
  4. Lockfile filenames (``uv.lock``, ``package-lock.json``, ``go.sum``, ...) -- matched by
     basename anywhere in the tree, never hardcoded to a single directory.
  5. Vendor/build directory name conventions (``vendor``, ``node_modules``, ``dist``,
     ``build``, ``__pycache__``, ...), found on disk.
  6. Detected codegen output: a script literally traces a string-literal path (a pathlib
     ``/`` chain or ``os.path.join``) into a ``write_text`` / ``write`` / ``json.dump`` call,
     naming a tracked file as ITS OWN write target.
  7. A tool-side list of language-convention immutable/fixture directory names
     (``migrations``, ``testdata``, ``__snapshots__``, ``fixtures``) -- required because the
     first six provably cannot produce these (see the R3 requirement / af-clean brainstorm
     B3): a plain ``migrations/`` directory is neither gitignored nor marked, but must never
     be treated as dead code or rewritten.

As a bonus 8th signal (folded under "vendored"), a README/NOTICE that explicitly says a
sibling directory was vendored (e.g. "vendored once into `sources/`") is honored: a directory
of third-party source dropped wholesale into the repo has no other structural signal, but the
repo's own documentation already admits it is not hand-authored here.

Every entry records WHICH signal(s) produced it and a human-readable detail, so the manifest
is always reviewable output (never a silent exclusion).
"""

from __future__ import annotations

import fnmatch
import os
import re
import subprocess
from dataclasses import dataclass, field
from pathlib import Path
from typing import Optional

# --------------------------------------------------------------------------- signal names

SIG_GITIGNORE = "gitignore"
SIG_GITATTRIBUTES = "gitattributes-linguist"
SIG_GENERATED_MARKER = "generated-marker"
SIG_LOCKFILE = "lockfile-filename"
SIG_VENDOR_DIR = "vendor-build-dir-convention"
SIG_IMMUTABLE_DIR = "language-convention-immutable-dir"
SIG_CODEGEN_OUTPUT = "codegen-output-traced"
SIG_VENDOR_README = "vendor-readme-declaration"

# --------------------------------------------------------------------------- tool-side lists

# Input #7: nothing in .gitignore/.gitattributes/markers/lockfiles/vendor-dir-names can ever
# produce these -- they are a plain per-language CONVENTION the tool must know about itself.
IMMUTABLE_DIR_NAMES = frozenset({"migrations", "testdata", "__snapshots__", "fixtures"})

# Input #5: conventional build/vendor/cache directory names. Deliberately excludes generic
# names ("bin", "obj") that collide with real source directories in many repos/languages.
VENDOR_DIR_NAMES = frozenset({
    "vendor", "node_modules", "dist", "build", ".venv", "venv", "__pycache__",
    ".next", ".nuxt", "target", ".terraform", ".parcel-cache", ".pytest_cache",
    ".mypy_cache", ".ruff_cache", ".tox", "site-packages", ".cache",
})

LOCKFILE_NAMES = frozenset({
    "uv.lock", "poetry.lock", "Pipfile.lock", "package-lock.json", "yarn.lock",
    "pnpm-lock.yaml", "Cargo.lock", "go.sum", "Gemfile.lock", "composer.lock",
    "mix.lock", "Podfile.lock",
})

_GENERATED_MARKER_PATTERNS = [
    re.compile(r"@generated", re.I),
    re.compile(r"do\s+not\s+edit", re.I),
    re.compile(r"auto-?generated", re.I),
    re.compile(r"code generated by", re.I),
    re.compile(r"this file (?:was|is) automatically generated", re.I),
    re.compile(r"generated by [\w.\-]+", re.I),
    re.compile(r"postgresql database dump", re.I),
    re.compile(r"mysql dump", re.I),
]

_VENDOR_README_PATTERN = re.compile(
    r"vendored\s+(?:once\s+)?(?:into|from)|third-party vendor", re.I
)

_STRING_LIT_RE = re.compile(r'"([^"\n]+)"|\'([^\'\n]+)\'')
_ASSIGN_RE = re.compile(r"^\s*([A-Za-z_]\w*)\s*=\s*(.+?)\s*$", re.MULTILINE)
_WRITE_CALL_TMPL = r"\b{var}\s*\.\s*(?:write_text|write_bytes|write)\s*\("
_JSON_DUMP_TMPL = r"json\.dump\([^,]+,\s*(?:open\([^)]*)?{var}\b"

_MAX_MARKER_SCAN_BYTES = 4096


@dataclass
class ExemptionEntry:
    """One exemption manifest entry.

    ``path`` is repo-relative (POSIX separators). A directory or an unresolved gitignore-style
    pattern is *not* required to exist on disk right now -- ``.gitignore``'s own declaration is
    evidence enough. ``signals`` lists every distinct signal (of the seven-plus-one) that
    independently justified this entry; ``details`` carries one human-readable citation per
    signal so the manifest is reviewable, never a silent exclusion.
    """

    path: str
    signals: list[str] = field(default_factory=list)
    details: list[str] = field(default_factory=list)

    def add_signal(self, signal: str, detail: str = "") -> None:
        if signal not in self.signals:
            self.signals.append(signal)
            self.details.append(detail)


@dataclass
class ExemptionManifest:
    """The derived exemption manifest: repo-relative path/pattern -> the entry for it."""

    entries: dict[str, ExemptionEntry] = field(default_factory=dict)

    def paths(self) -> list[str]:
        return sorted(e.path for e in self.entries.values())

    def __contains__(self, path: object) -> bool:
        return str(path).rstrip("/") in self.entries

    def signals_for(self, path: str) -> list[str]:
        entry = self.entries.get(path.rstrip("/"))
        return list(entry.signals) if entry else []

    def report(self) -> str:
        """A human-readable report: every entry, with the signal(s) that produced it -- the
        acceptance condition's "every manifest entry is listed in the report with the signal
        that produced it"."""
        lines = ["# af-clean exemption manifest", ""]
        if not self.entries:
            lines.append("(no exemptions derived)")
            return "\n".join(lines)
        for key in sorted(self.entries):
            entry = self.entries[key]
            for signal, detail in zip(entry.signals, entry.details):
                suffix = f" -- {detail}" if detail else ""
                lines.append(f"- `{entry.path}`: {signal}{suffix}")
        return "\n".join(lines)


def _add(manifest: ExemptionManifest, path: str, signal: str, detail: str = "") -> None:
    if not path:
        return
    norm = path.replace(os.sep, "/")
    key = norm.rstrip("/")
    if not key:
        return
    entry = manifest.entries.get(key)
    if entry is None:
        entry = ExemptionEntry(path=norm)
        manifest.entries[key] = entry
    entry.add_signal(signal, detail)


# --------------------------------------------------------------------------- git plumbing

def _git(repo_root: Path, *args: str) -> str:
    try:
        proc = subprocess.run(
            ["git", "-C", str(repo_root), *args],
            capture_output=True, text=True, timeout=60,
        )
    except (OSError, subprocess.SubprocessError):
        return ""
    return proc.stdout if proc.returncode == 0 else ""


def _tracked_files(repo_root: Path) -> list[str]:
    out = _git(repo_root, "ls-files")
    return [line for line in out.splitlines() if line]


# --------------------------------------------------------------------------- signal 1: gitignore

def _signal_gitignore(repo_root: Path, manifest: ExemptionManifest) -> None:
    for gi in sorted(repo_root.rglob(".gitignore")):
        if ".git" in gi.relative_to(repo_root).parts:
            continue
        rel_dir = gi.parent.relative_to(repo_root)
        try:
            lines = gi.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        cite = str(gi.relative_to(repo_root))
        for raw in lines:
            line = raw.strip()
            if not line or line.startswith("#") or line.startswith("!"):
                continue  # negations opt files back IN -- never an exemption signal
            pattern = line
            rel = f"{rel_dir}/{pattern}" if str(rel_dir) != "." else pattern
            _add(manifest, rel, SIG_GITIGNORE, f"declared in {cite}: {pattern!r}")


# --------------------------------------------------------------------------- signal 2: gitattributes

def _signal_gitattributes(repo_root: Path, manifest: ExemptionManifest, tracked: list[str]) -> None:
    for ga in sorted(repo_root.rglob(".gitattributes")):
        if ".git" in ga.relative_to(repo_root).parts:
            continue
        rel_dir = ga.parent.relative_to(repo_root)
        try:
            lines = ga.read_text(encoding="utf-8", errors="replace").splitlines()
        except OSError:
            continue
        for raw in lines:
            line = raw.strip()
            if not line or line.startswith("#"):
                continue
            parts = line.split()
            if len(parts) < 2:
                continue
            pattern, attrs = parts[0], parts[1:]
            linguist_attrs = [
                a.split("=")[0] for a in attrs
                if a in ("linguist-generated", "linguist-vendored")
                or a.startswith(("linguist-generated=", "linguist-vendored="))
            ]
            if not linguist_attrs:
                continue
            glob = f"{rel_dir}/{pattern}" if str(rel_dir) != "." else pattern
            for f in tracked:
                if fnmatch.fnmatch(f, glob) or fnmatch.fnmatch(Path(f).name, pattern):
                    _add(manifest, f, SIG_GITATTRIBUTES,
                         f"{ga.relative_to(repo_root)}: {pattern} {linguist_attrs[0]}")


# --------------------------------------------------------------------------- signal 3: generated markers

def _signal_generated_markers(repo_root: Path, manifest: ExemptionManifest, tracked: list[str]) -> None:
    for f in tracked:
        path = repo_root / f
        try:
            if not path.is_file():
                continue
            # Only the HEAD bytes are ever read, regardless of total file size, so a large
            # generated dump (e.g. an 11MB pg_dump) is scanned as cheaply as a tiny file --
            # there is no reason to skip it by size.
            head = path.open("rb").read(_MAX_MARKER_SCAN_BYTES)
        except OSError:
            continue
        text = head.decode("utf-8", errors="ignore")
        for pat in _GENERATED_MARKER_PATTERNS:
            m = pat.search(text)
            if m:
                _add(manifest, f, SIG_GENERATED_MARKER, f"matched {m.group(0)!r} near top of file")
                break


# --------------------------------------------------------------------------- signal 4: lockfiles

def _signal_lockfiles(repo_root: Path, manifest: ExemptionManifest, tracked: list[str]) -> None:
    for f in tracked:
        if Path(f).name in LOCKFILE_NAMES:
            _add(manifest, f, SIG_LOCKFILE, f"lockfile filename {Path(f).name!r}")


# --------------------------------------------------------------------------- signal 5 / 7: dir walk

def _walk_dirs(repo_root: Path):
    for dirpath, dirnames, _filenames in os.walk(repo_root):
        if ".git" in dirnames:
            dirnames.remove(".git")
        yield dirpath, dirnames


def _signal_vendor_dirs(repo_root: Path, manifest: ExemptionManifest) -> None:
    for dirpath, dirnames in _walk_dirs(repo_root):
        for d in list(dirnames):
            if d in VENDOR_DIR_NAMES:
                rel = (Path(dirpath) / d).relative_to(repo_root)
                _add(manifest, f"{rel}/", SIG_VENDOR_DIR,
                     f"conventional build/vendor directory name {d!r}")
                dirnames.remove(d)  # a vendor dir's insides are not separately walked


def _signal_immutable_dirs(repo_root: Path, manifest: ExemptionManifest) -> None:
    for dirpath, dirnames in _walk_dirs(repo_root):
        for d in list(dirnames):
            if d in IMMUTABLE_DIR_NAMES:
                rel = (Path(dirpath) / d).relative_to(repo_root)
                _add(manifest, f"{rel}/", SIG_IMMUTABLE_DIR,
                     f"language-convention immutable/fixture directory name {d!r}")
                dirnames.remove(d)


# --------------------------------------------------------------------------- signal 6: traced codegen output

def _literal_segments(expr: str) -> Optional[list[str]]:
    """Extract the literal path segments from a pathlib ``/``-join chain, e.g.
    ``_REPO_ROOT / "a" / "b.json"`` -> ``["a", "b.json"]``. A non-literal, non-bare-identifier
    segment (an f-string, a function call, ...) aborts the trace -- return ``None`` rather than
    guess."""
    parts = [p.strip() for p in expr.split("/")]
    if len(parts) < 2:
        return None
    segs: list[str] = []
    for p in parts:
        if p[:1] in ("'", '"'):
            m = _STRING_LIT_RE.match(p)
            if not m:
                return None
            segs.append(next(g for g in m.groups() if g is not None))
        elif re.fullmatch(r"[A-Za-z_]\w*", p):
            continue  # a bare identifier (e.g. a repo-root variable) -- not a literal segment
        else:
            return None
    return segs or None


def _os_path_join_segments(expr: str) -> Optional[list[str]]:
    m = re.search(r"os\.path\.join\((.+)\)\s*$", expr)
    if not m:
        return None
    segs: list[str] = []
    for arg in m.group(1).split(","):
        arg = arg.strip()
        lm = _STRING_LIT_RE.match(arg)
        if lm:
            segs.append(next(g for g in lm.groups() if g is not None))
        elif re.fullmatch(r"[A-Za-z_][\w.]*", arg):
            continue
        else:
            return None
    return segs or None


def _signal_codegen_output(repo_root: Path, manifest: ExemptionManifest, tracked: list[str]) -> None:
    tracked_set = set(tracked)
    for f in tracked:
        if not f.endswith(".py"):
            continue
        path = repo_root / f
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if not any(tok in text for tok in ("write_text(", "write_bytes(", "json.dump(", ".write(")):
            continue
        assigns: dict[str, list[str]] = {}
        for m in _ASSIGN_RE.finditer(text):
            var, expr = m.group(1), m.group(2)
            segs = None
            if " / " in expr:
                segs = _literal_segments(expr)
            elif "os.path.join(" in expr:
                segs = _os_path_join_segments(expr)
            if segs:
                assigns[var] = segs
        for var, segs in assigns.items():
            rel = "/".join(segs)
            target = next((t for t in tracked_set if t == rel or t.endswith("/" + rel)), None)
            if target is None:
                continue
            if re.search(_WRITE_CALL_TMPL.format(var=re.escape(var)), text) or \
               re.search(_JSON_DUMP_TMPL.format(var=re.escape(var)), text):
                _add(manifest, target, SIG_CODEGEN_OUTPUT,
                     f"written by {f} (traced literal path-join to a write call)")


# --------------------------------------------------------------------------- vendor README declaration

_README_NAMES = {"readme.md", "notice", "notice.md", "vendor", "vendor.md"}


def _signal_vendor_readme(repo_root: Path, manifest: ExemptionManifest, tracked: list[str]) -> None:
    for f in tracked:
        if Path(f).name.lower() not in _README_NAMES:
            continue
        path = repo_root / f
        try:
            text = path.read_text(encoding="utf-8", errors="ignore")
        except OSError:
            continue
        if not _VENDOR_README_PATTERN.search(text):
            continue
        parent = path.parent
        backtick_tokens = re.findall(r"`([\w./\-]+)`", text)
        found_any = False
        for token in backtick_tokens:
            candidate = (parent / token).resolve()
            try:
                candidate.relative_to(repo_root)
            except ValueError:
                continue
            if candidate.exists() and candidate != path:
                rel = candidate.relative_to(repo_root)
                suffix = "/" if candidate.is_dir() else ""
                _add(manifest, f"{rel}{suffix}", SIG_VENDOR_README,
                     f"{f} declares vendored content at `{token}`")
                found_any = True
        if not found_any:
            # The README admits vendoring but names no specific sub-path we could resolve --
            # fall back to exempting its own directory's non-README siblings, still citing why.
            for sibling in sorted(parent.iterdir()):
                if sibling == path:
                    continue
                rel = sibling.relative_to(repo_root)
                suffix = "/" if sibling.is_dir() else ""
                _add(manifest, f"{rel}{suffix}", SIG_VENDOR_README,
                     f"{f} declares vendored content (no specific sub-path named)")


# --------------------------------------------------------------------------- entry point

def derive_exemption_manifest(repo_root: "str | Path") -> ExemptionManifest:
    """Derive the exemption manifest for ``repo_root`` from all eight signals.

    Every entry is justified by at least one signal recorded on it (:meth:`ExemptionManifest.report`
    surfaces each), so the manifest is reviewable output, never a silent exclusion.
    """
    root = Path(repo_root).resolve()
    manifest = ExemptionManifest()
    tracked = _tracked_files(root)

    _signal_gitignore(root, manifest)
    _signal_gitattributes(root, manifest, tracked)
    _signal_generated_markers(root, manifest, tracked)
    _signal_lockfiles(root, manifest, tracked)
    _signal_vendor_dirs(root, manifest)
    _signal_immutable_dirs(root, manifest)
    _signal_codegen_output(root, manifest, tracked)
    _signal_vendor_readme(root, manifest, tracked)

    return manifest
