"""R3 acceptance: af-clean's automatic exemption-manifest derivation.

Acceptance (verbatim from the ticket): on the praxis repo the derived manifest contains
``migrations/``, ``praxis_kg_dump.sql``, ``uv.lock``, ``package-lock.json``, ``mock-*.json``,
the ``skill_unification`` sources tree, ``go.sum``, ``testdata/`` and ``infra/cdk.out/`` with
nothing hand-authored in the target repo; and every manifest entry is listed in the report
with the signal that produced it.

Unit tests below exercise each of the seven input signals (plus the vendor-README bonus lane)
in isolation on a synthetic fixture repo, so a regression in one signal fails at the signal
that broke rather than only at the integration level.
"""

from __future__ import annotations

import subprocess
from pathlib import Path

from agent_factory.af_clean.exemptions import (
    SIG_CODEGEN_OUTPUT,
    SIG_GENERATED_MARKER,
    SIG_GITATTRIBUTES,
    SIG_GITIGNORE,
    SIG_IMMUTABLE_DIR,
    SIG_LOCKFILE,
    SIG_VENDOR_DIR,
    SIG_VENDOR_README,
    derive_exemption_manifest,
)

_REPO_ROOT = Path(__file__).resolve().parent.parent.parent


def _write(path: Path, content: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    path.write_text(content, encoding="utf-8")


def _init_git_repo(repo: Path) -> None:
    subprocess.run(["git", "init", "-q"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.email", "test@example.com"], cwd=repo, check=True)
    subprocess.run(["git", "config", "user.name", "Test"], cwd=repo, check=True)
    subprocess.run(["git", "add", "-A"], cwd=repo, check=True)
    subprocess.run(["git", "commit", "-q", "-m", "init"], cwd=repo, check=True)


# --------------------------------------------------------------------------- integration: the real repo


def test_acceptance_praxis_repo_manifest_contains_required_entries():
    manifest = derive_exemption_manifest(_REPO_ROOT)
    paths = manifest.paths()

    assert any(p.rstrip("/") == "migrations" for p in paths), paths
    assert "praxis_kg_dump.sql" in paths
    assert "uv.lock" in paths
    assert any(p.endswith("package-lock.json") for p in paths), paths
    assert any(Path(p).name.startswith("mock-") and p.endswith(".json") for p in paths), paths
    assert any("skill_unification/sources" in p for p in paths), paths
    assert any(p.endswith("go.sum") for p in paths), paths
    assert any(p.rstrip("/").endswith("testdata") for p in paths), paths
    assert "infra/cdk.out/" in paths or "infra/cdk.out" in {p.rstrip("/") for p in paths}, paths

    # nothing hand-authored: every entry carries at least one cited signal.
    report = manifest.report()
    for p in paths:
        assert manifest.signals_for(p), f"{p} has no signal recorded"
        assert f"`{p}`" in report, f"{p} missing from the report"


def test_report_names_the_signal_for_every_entry():
    manifest = derive_exemption_manifest(_REPO_ROOT)
    report = manifest.report()
    for path, entry in manifest.entries.items():
        for signal in entry.signals:
            assert signal in report


# --------------------------------------------------------------------------- signal 1: gitignore


def test_gitignore_signal_exempts_ignored_pattern_even_if_absent(tmp_path):
    repo = tmp_path / "repo"
    _write(repo / ".gitignore", "build/\n*.generated.json\n")
    _write(repo / "README.md", "hi\n")
    _init_git_repo(repo)

    manifest = derive_exemption_manifest(repo)
    assert "build/" in manifest.paths()
    assert SIG_GITIGNORE in manifest.signals_for("build/")
    # never built on disk -- still exempt, because the repo itself declares it derived output.
    assert not (repo / "build").exists()


# --------------------------------------------------------------------------- signal 2: gitattributes


def test_gitattributes_linguist_generated_signal(tmp_path):
    repo = tmp_path / "repo"
    _write(repo / ".gitattributes", "vendor.min.js linguist-generated\n")
    _write(repo / "vendor.min.js", "console.log(1)\n")
    _write(repo / "app.js", "console.log(2)\n")
    _init_git_repo(repo)

    manifest = derive_exemption_manifest(repo)
    assert "vendor.min.js" in manifest.paths()
    assert SIG_GITATTRIBUTES in manifest.signals_for("vendor.min.js")
    assert "app.js" not in manifest.paths()


# --------------------------------------------------------------------------- signal 3: generated markers


def test_generated_marker_signal_catches_dump_header_and_at_generated(tmp_path):
    repo = tmp_path / "repo"
    _write(repo / "dump.sql", "--\n-- PostgreSQL database dump\n--\n\nSELECT 1;\n")
    _write(repo / "gen.py", "# @generated by codegen tool\nX = 1\n")
    _write(repo / "hand.py", "X = 1\n")
    _init_git_repo(repo)

    manifest = derive_exemption_manifest(repo)
    assert SIG_GENERATED_MARKER in manifest.signals_for("dump.sql")
    assert SIG_GENERATED_MARKER in manifest.signals_for("gen.py")
    assert "hand.py" not in manifest.paths()


# --------------------------------------------------------------------------- signal 4: lockfiles


def test_lockfile_signal_matches_by_basename_anywhere(tmp_path):
    repo = tmp_path / "repo"
    _write(repo / "infra" / "package-lock.json", "{}\n")
    _write(repo / "go.sum", "\n")
    _init_git_repo(repo)

    manifest = derive_exemption_manifest(repo)
    assert "infra/package-lock.json" in manifest.paths()
    assert "go.sum" in manifest.paths()
    assert SIG_LOCKFILE in manifest.signals_for("infra/package-lock.json")


# --------------------------------------------------------------------------- signal 5: vendor dir conventions


def test_vendor_dir_convention_signal(tmp_path):
    repo = tmp_path / "repo"
    _write(repo / "node_modules" / "left-pad" / "index.js", "module.exports = 1;\n")
    _write(repo / "src" / "index.js", "1;\n")
    _init_git_repo(repo)

    manifest = derive_exemption_manifest(repo)
    assert "node_modules/" in manifest.paths()
    assert SIG_VENDOR_DIR in manifest.signals_for("node_modules/")
    assert "src/index.js" not in manifest.paths()


# --------------------------------------------------------------------------- signal 6: traced codegen output


def test_codegen_output_signal_traces_pathlib_join_to_write_call(tmp_path):
    repo = tmp_path / "repo"
    _write(repo / "public" / "mock-data.json", "{}\n")
    _write(
        repo / "scripts" / "export_mock.py",
        "from pathlib import Path\n"
        "_ROOT = Path(__file__).resolve().parent.parent\n"
        '_TARGET = _ROOT / "public" / "mock-data.json"\n'
        "\n"
        "def main():\n"
        '    _TARGET.write_text("{}", encoding="utf-8")\n',
    )
    _init_git_repo(repo)

    manifest = derive_exemption_manifest(repo)
    assert "public/mock-data.json" in manifest.paths()
    assert SIG_CODEGEN_OUTPUT in manifest.signals_for("public/mock-data.json")


# --------------------------------------------------------------------------- signal 7: immutable dir names


def test_immutable_dir_signal_catches_migrations_and_nested_testdata(tmp_path):
    repo = tmp_path / "repo"
    _write(repo / "migrations" / "0001_init.sql", "-- init\n")
    _write(repo / "pkg" / "internal" / "testdata" / "fixture.txt", "x\n")
    _init_git_repo(repo)

    manifest = derive_exemption_manifest(repo)
    assert "migrations/" in manifest.paths()
    assert "pkg/internal/testdata/" in manifest.paths()
    assert SIG_IMMUTABLE_DIR in manifest.signals_for("migrations/")


# --------------------------------------------------------------------------- vendor README bonus lane


def test_vendor_readme_signal_resolves_backtick_named_subdir(tmp_path):
    repo = tmp_path / "repo"
    _write(
        repo / "third_party" / "README.md",
        "Every skill file was vendored once into `sources/`:\n",
    )
    _write(repo / "third_party" / "sources" / "a.md", "content\n")
    _init_git_repo(repo)

    manifest = derive_exemption_manifest(repo)
    assert "third_party/sources/" in manifest.paths()
    assert SIG_VENDOR_README in manifest.signals_for("third_party/sources/")
